name: Manual trigger with input

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL for curl'
        required: true

jobs:
  run-curl:
    runs-on: ubuntu-latest
    steps:
    - name: Run curl
      run: curl ${{ github.event.inputs.target_url }}

    - name: Upload response as artifact
      uses: actions/upload-artifact@v2
      with:
        name: server-response
        path: response.txt
