name: Manual trigger with input

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'input URL'
        required: true

jobs:
  request-curl:
    runs-on: ubuntu-latest
    steps:
    - name: request-curl
      run: |
        curl -s ${{ github.event.inputs.target_url }} > response.txt

    - name: Upload response as artifact
      uses: actions/upload-artifact@v2
      with:
        name: server-response
        path: response.txt
