name: Manual Curl URL

on:
  workflow_dispatch:
    inputs:
      httpMethod:
        description: 'HTTP Method'
        required: true
      url:
        description: 'input URL'
        required: true

jobs:
  request-curl:
    runs-on: ubuntu-latest
    steps:
    - name: request-curl
      run: |
        curl -X ${{ github.event.inputs.httpMethod }} ${{ github.event.inputs.url }} > response.txt

    - name: Upload response as artifact
      uses: actions/upload-artifact@v2
      with:
        name: server-response
        path: response.txt
